# yamllint disable rule:indentation
---
-   id: cr-manager
    name: Update Copyright Headers
    description: Adds, updates, or checks copyright headers using the cr-manager tool.
    entry: cr-manager
    language: python
    language_version: python3
    files: '(?i)((^|.*/)(Dockerfile|Jenkinsfile)$|.*/(dockerfile|jenkinsfile)/.*|.*\.(sh|bash|py|gradle|groovy|java|c|cpp|cxx|h|hpp|hxx)$)'
    args: ["--update"]
