# yamllint disable rule:indentation
-   id: update-copyright
    name: Update Copyright Headers (cr-manager)
    description: Adds, updates, or checks copyright headers using the cr-manager tool.
    # Use the console script defined in pyproject.toml
    entry: cr-manager
    language: python
    language_version: python3
    types: [ python, java, groovy, shell ] # Corrected key
